import numpy as np
import cv2
import matplotlib.pyplot as plt
from src.utils import load_image
from scipy.stats import kurtosis, skew
from skimage.measure import shannon_entropy
from pathlib import Path
from skimage.transform import radon
from skimage.measure import regionprops, label as sk_label


def extract_rois(skeleton, img_shape, roi_size=80, total_rois=100):
    """
    Extracts exactly `total_rois` fixed-size ROIs along a vessel skeleton.
    This function is pure and can be used identically during training and inference.

    Args:
        skeleton (np.ndarray): Binary image of the skeletonized vessel.
        img_shape (tuple): Shape of the original image (height, width).
        roi_size (int): The height and width of the square ROI.
        total_rois (int): Total number of ROIs to sample (default 100).

    Returns:
        list of dict: Exactly `total_rois` candidate bounding boxes.
    """
    half_size = roi_size // 2

    # 1. Sort the skeleton points (The "Walker" Algorithm)
    y_coords, x_coords = np.where(skeleton)
    available_points = set(zip(x_coords, y_coords))
    ordered_points = []

    if len(available_points) > 0:
        actual = list(available_points)[0]
        ordered_points.append(actual)
        available_points.remove(actual)

        while len(available_points) > 0:
            missing_points = np.array(list(available_points))
            dists = np.sum((missing_points - np.array(actual)) ** 2, axis=1)
            idx_min = np.argmin(dists)

            actual = tuple(missing_points[idx_min])
            ordered_points.append(actual)
            available_points.remove(actual)

    # 2. Sample Equidistant points along the skeleton
    final_boxes = []
    total_points = len(ordered_points)

    if total_points > 0 and total_rois > 0:
        equidist_idxs = np.linspace(0, total_points - 1, total_rois, dtype=int)

        for idx in equidist_idxs:
            pt_x, pt_y = ordered_points[idx]
            final_boxes.append(_create_fixed_box(pt_x, pt_y, half_size, img_shape))

    return final_boxes


def _create_fixed_box(center_x, center_y, half_size, img_shape):
    """Helper function to create a bounding box and clamp it to image boundaries."""
    xmin = int(center_x - half_size)
    ymin = int(center_y - half_size)
    xmax = int(center_x + half_size)
    ymax = int(center_y + half_size)

    # Dynamic boundary adjustment to ensure the box is ALWAYS exactly 80x80
    # If it hits a border, we shift the box inward rather than cropping it
    if xmin < 0:
        xmax += abs(xmin)
        xmin = 0
    if ymin < 0:
        ymax += abs(ymin)
        ymin = 0
    if xmax > img_shape[1]:
        xmin -= (xmax - img_shape[1])
        xmax = img_shape[1]
    if ymax > img_shape[0]:
        ymin -= (ymax - img_shape[0])
        ymax = img_shape[0]

    return {'xmin': xmin, 'ymin': ymin, 'xmax': xmax, 'ymax': ymax}


def label_rois(candidate_rois, gt_boxes, threshold=0.50):
    """
    Labels a list of candidate ROIs based on their overlap with the original
    ground truth bounding boxes.

    Args:
        candidate_rois (list of dict): The 80x80 ROIs generated by extract_rois.
        gt_boxes (list of dict): The ORIGINAL, variable-sized ground truth boxes from the XML.
        threshold (float): The minimum overlap percentage required to label as stenosis.

    Returns:
        list of int: A list of labels (1 for STENOSIS, 0 for HEALTHY) corresponding
                     to each ROI in candidate_rois.
    """
    labels = []

    for roi in candidate_rois:
        is_stenosis = False

        for gt_box in gt_boxes:
            # Calculate intersection coordinates
            inter_xmin = max(roi['xmin'], gt_box['xmin'])
            inter_ymin = max(roi['ymin'], gt_box['ymin'])
            inter_xmax = min(roi['xmax'], gt_box['xmax'])
            inter_ymax = min(roi['ymax'], gt_box['ymax'])

            # Calculate intersection dimensions
            inter_w = max(0, inter_xmax - inter_xmin)
            inter_h = max(0, inter_ymax - inter_ymin)
            area_interseccion = inter_w * inter_h

            # Calculate original GT box area
            area_box_original = (gt_box['xmax'] - gt_box['xmin']) * (gt_box['ymax'] - gt_box['ymin'])

            # Check if threshold is met
            if area_box_original > 0 and area_interseccion >= threshold * area_box_original:
                is_stenosis = True
                break  # If it matches one GT box, no need to check others

        # Append 1 for STENOSIS, 0 for HEALTHY
        labels.append(1 if is_stenosis else 0)

    return labels


def build_gabor_bank(ksize=31, n_sizes=4, n_orientations=8):
    """
    Builds a bank of Gabor filters at various scales and orientations.

    Parameters:
        ksize          : int, the size of the kernel (e.g., 31 means a 31x31 matrix)
        n_sizes        : int, number of different frequencies/thicknesses to detect
        n_orientations : int, number of angles (e.g., 12 means every 15 degrees)

    Returns:
        filters        : list of cv2 Gabor kernels
    """
    filters = []

    # 1. Calculate orientations (theta) - e.g., 12 steps from 0 to 180 degrees (Pi)
    thetas = np.arange(0, np.pi, np.pi / n_orientations)

    # 2. Calculate wavelengths (lambda) - controls the thickness of the vessel we want to detect
    # A good range for an 80x80 image is wavelengths from roughly 4 pixels up to 16 pixels
    lambdas = np.linspace(4, 20, n_sizes)

    # Default parameters for medical imaging Gabor filters
    gamma = 0.5  # Spatial aspect ratio (0.5 makes it slightly elliptical, good for tubes)
    psi = 0  # Phase offset (0 makes it perfectly centered)

    for theta in thetas:
        for lamda in lambdas:
            # Sigma controls the size of the Gaussian envelope.
            # Tying it to lambda ensures the filter scales properly.
            sigma = 0.56 * lamda

            # Generate the kernel
            kernel = cv2.getGaborKernel(
                (ksize, ksize),
                sigma,
                theta,
                lamda,
                gamma,
                psi,
                ktype=cv2.CV_32F  # Using 32-bit floats for high precision
            )

            # Normalize the kernel (helps ensure different scales have comparable energy)
            kernel /= 1.5 * kernel.sum() if kernel.sum() != 0 else 1.0

            filters.append(kernel)

    print(f"Built Gabor bank with {len(filters)} filters ({n_orientations} orientations x {n_sizes} sizes).")
    return filters

def extract_stats(patch):
    """
    Extracts 6 statistical features from a 2D array.
    """
    flat = patch.flatten()
    mean_val     = np.mean(flat)
    var_val      = np.var(flat)
    entropy_val  = shannon_entropy(patch)          # skimage handles 2D directly
    energy_val   = np.sum(flat ** 2)               # sum of squared responses
    kurtosis_val = kurtosis(flat, fisher=True)     # excess kurtosis (normal=0)
    skewness_val = skew(flat)
    return [mean_val, var_val, entropy_val, energy_val, kurtosis_val, skewness_val]


def apply_gabor_and_extract_features(roi, filters):
    """
    Applies a bank of Gabor filters to a single ROI and extracts:
      - 6 stats from the full filtered ROI
      - 6 stats from each of 4 non-overlapping tiles (top-left, top-right,
        bottom-left, bottom-right)

    Total features per filter = 6 (global) + 4 x 6 (tiles) = 30
    Total features overall    = 30 x len(filters)

    Parameters:
        roi     : 2D numpy array (e.g. 80x80 image crop)
        filters : list of cv2 Gabor kernels from build_gabor_bank()

    Returns:
        feature_vector : 1D numpy array
    """
    features = []

    for kernel in filters:
        filtered_img = cv2.filter2D(roi, cv2.CV_32F, kernel,
                                    borderType=cv2.BORDER_REFLECT)
        # --- Global features (6) ---
        features.extend(extract_stats(filtered_img))

        # --- Tile features (4 tiles x 6 = 24) ---
        h, w = filtered_img.shape
        h2, w2 = h // 2, w // 2

        tiles = [
            filtered_img[:h2,  :w2 ],   # top-left
            filtered_img[:h2,  w2: ],   # top-right
            filtered_img[h2:,  :w2 ],   # bottom-left
            filtered_img[h2:,  w2: ],   # bottom-right
        ]

        for tile in tiles:
            features.extend(extract_stats(tile))

    return np.array(features, dtype=np.float32)

def extract_raw_roi_features(roi):
    """
    Extracts 6 statistical features from the raw (unfiltered) ROI
    and from its 4 non-overlapping tiles.

    Parameters:
        roi : 2D numpy array of shape (H, W)

    Returns:
        feature_vector : 1D numpy array of 30 features
                         6 (global) + 4 x 6 (tiles)
    """
    features = []
    # --- Global features (6) ---
    features.extend(extract_stats(roi))

    # --- Tile features (4 x 6 = 24) ---
    h, w = roi.shape
    h2, w2 = h // 2, w // 2

    tiles = [
        roi[:h2, :w2],   # top-left
        roi[:h2, w2:],   # top-right
        roi[h2:, :w2],   # bottom-left
        roi[h2:, w2:],   # bottom-right
    ]

    for tile in tiles:
        features.extend(extract_stats(tile))

    return np.array(features, dtype=np.float32)

def _order_skeleton_points(skeleton_roi):
    """
    Orders skeleton pixels sequentially using a nearest-neighbour walk,
    consistent with the approach used in extract_rois().

    Returns:
        ordered_points : list of (x, y) tuples in traversal order
    """
    y_coords, x_coords = np.where(skeleton_roi)
    available = set(zip(x_coords, y_coords))
    ordered   = []

    if not available:
        return ordered

    current = next(iter(available))
    ordered.append(current)
    available.remove(current)

    while available:
        pts  = np.array(list(available))
        dists = np.sum((pts - np.array(current)) ** 2, axis=1)
        current = tuple(pts[np.argmin(dists)])
        ordered.append(current)
        available.remove(current)

    return ordered


def extract_width_ratio_feature(mask_roi, skeleton_roi, tangent_window=5):
    """
    Measures vessel width at each skeleton point within the ROI by casting
    perpendicular rays into the binary mask, then returns max_width / min_width.

    This ratio is particularly informative for stenosis detection: a healthy
    vessel has a ratio close to 1.0, while a stenotic vessel shows a high ratio
    due to the local narrowing.

    Parameters:
        mask_roi        : 2D binary numpy array (H, W) — vessel mask crop
        skeleton_roi    : 2D binary numpy array (H, W) — skeleton crop
        tangent_window  : int, number of neighbouring points used to estimate
                          the local tangent direction at each skeleton point

    Returns:
        ratio : float, max_width / min_width across all skeleton points in the ROI.
                Returns 1.0 if the skeleton has fewer than 2 points (degenerate case).
    """
    ordered = _order_skeleton_points(skeleton_roi)

    if len(ordered) < 2:
        return 1.0

    h, w = mask_roi.shape
    widths = []

    for i, (px, py) in enumerate(ordered):

        # --- Estimate local tangent via a symmetric window ---
        i_start = max(0, i - tangent_window)
        i_end   = min(len(ordered) - 1, i + tangent_window)
        dx = ordered[i_end][0] - ordered[i_start][0]
        dy = ordered[i_end][1] - ordered[i_start][1]

        norm = np.sqrt(dx ** 2 + dy ** 2)
        if norm == 0:
            continue

        # Perpendicular direction (rotate tangent by 90 degrees)
        perp_x = -dy / norm
        perp_y =  dx / norm

        # --- Cast rays in both perpendicular directions ---
        width = 1  # count the skeleton pixel itself
        for sign in (1, -1):
            step = 1
            while True:
                nx = int(round(px + sign * perp_x * step))
                ny = int(round(py + sign * perp_y * step))
                if nx < 0 or nx >= w or ny < 0 or ny >= h:
                    break
                if mask_roi[ny, nx] == 0:
                    break
                width += 1
                step  += 1

        widths.append(width)

    if not widths:
        return 1.0

    min_w = min(widths)
    max_w = max(widths)

    # Guard against degenerate masks where min width is 0
    if min_w == 0:
        return 1.0

    return float(max_w / min_w)

def build_feature_column_names(n_filters, stat_names, tile_labels):
    """
    Generates ordered column names matching the feature vector layout.

    - parameters:
    n_filters   : int, number of Gabor filters
    stat_names  : list of str, names of the statistical features
    tile_labels : list of str, labels for the 4 tiles (e.g., ['tl', 'tr', 'bl', 'br'])
    """

    cols = []

    # --- Raw ROI features (30) ---
    for stat in stat_names:
        cols.append(f"raw_global_{stat}")
    for tile in tile_labels:
        for stat in stat_names:
            cols.append(f"raw_{tile}_{stat}")

    # --- Gabor features (n_filters x 30) ---
    for i in range(n_filters):
        for stat in stat_names:
            cols.append(f"gabor_f{i}_global_{stat}")
        for tile in tile_labels:
            for stat in stat_names:
                cols.append(f"gabor_f{i}_{tile}_{stat}")

    # --- Width ratio (1) ---
    cols.append("width_ratio")

    return cols


def plot_gabor_response_grid(roi, gabor_bank, title, n_orientations=12, n_sizes=6):
    """
    Applies 72 Gabor filters to an ROI and displays the responses in a
    structured 12 (orientations) x 6 (scales) grid.
    """
    # Re-calculate parameters for labels
    thetas = np.arange(0, np.pi, np.pi / n_orientations)
    lambdas = np.linspace(4, 18, n_sizes)

    # Setup the figure grid
    fig, axes = plt.subplots(n_orientations, n_sizes, figsize=(14, 24))
    fig.suptitle(title, fontsize=18, fontweight='bold', y=0.92)

    # Plot the original ROI in a text box style on top or just print it out
    for i, theta in enumerate(thetas):
        deg = int(np.degrees(theta))
        for j, lamda in enumerate(lambdas):
            ax = axes[i, j]

            # Map back to the linear filter bank array
            filter_idx = i * n_sizes + j
            kernel = gabor_bank[filter_idx]

            # Apply Gabor Filter (Mirror padding)
            filtered_img = cv2.filter2D(roi, cv2.CV_32F, kernel, borderType=cv2.BORDER_REFLECT)

            # Show response map
            ax.imshow(filtered_img, cmap='gray')
            ax.axis('off')

            # Set labels on the borders of the grid for clean interpretation
            if i == 0:
                ax.set_title(f"Size {j + 1}\n($\lambda$={lamda:.1f})", fontsize=10)
            if j == 0:
                ax.text(-15, 40, f"{deg}°", va='center', ha='right', fontsize=12, fontweight='bold')

    plt.tight_layout()
    plt.show()

def process_one_image_coords(args):
    """
    Top-level worker for ProcessPoolExecutor — picklable because it lives in
    the module, not inside a notebook cell.

    Args:
        args : tuple of (img_path, mask_path, skel_path, gt_boxes, roi_size,
                         half_size, labeling_threshold)

    Returns:
        list of dicts with ROI coordinate rows, or [] on failure.
    """
    import time
    import traceback

    img_path, mask_path, skel_path, gt_boxes, roi_size, half_size, labeling_threshold = args

    try:
        t_start = time.time()
        print(f"[WORKER] ── START ── {img_path}", flush=True)

        # ── Load images ───────────────────────────────────────────
        img = load_image(img_path)
        print(f"[WORKER]   img loaded      : {img is not None}"
              f" | shape={img.shape if img is not None else 'N/A'}", flush=True)

        skeleton = load_image(skel_path)
        print(f"[WORKER]   skeleton loaded : {skeleton is not None}"
              f" | shape={skeleton.shape if skeleton is not None else 'N/A'}", flush=True)

        if img is None or skeleton is None:
            print(f"[WORKER]   SKIP — None load for {img_path}", flush=True)
            return []

        # ── Image metadata ────────────────────────────────────────
        img_shape  = img.shape[:2]
        p          = Path(img_path)
        patient_id = p.parts[-3]
        serie_id   = p.parts[-2]
        frame_stem = p.stem.replace('_processed', '')
        image_name = f"{patient_id}_{serie_id}_{frame_stem}"

        y_coords, x_coords = np.where(skeleton)
        n_skel_pixels = len(x_coords)
        print(f"[WORKER]   image_name     : {image_name}", flush=True)
        print(f"[WORKER]   img_shape      : {img_shape}", flush=True)
        print(f"[WORKER]   skeleton px    : {n_skel_pixels}", flush=True)

        # ── extract_rois ──────────────────────────────────────────
        print(f"[WORKER]   calling extract_rois ...", flush=True)
        t0 = time.time()
        sampled_boxes = extract_rois(skeleton, img_shape, roi_size=roi_size, total_rois=100)
        print(f"[WORKER]   extract_rois done in {time.time()-t0:.2f}s"
              f" — {len(sampled_boxes)} boxes", flush=True)

        # ── label_rois ────────────────────────────────────────────
        print(f"[WORKER]   calling label_rois (gt_boxes={len(gt_boxes)}) ...", flush=True)
        t0 = time.time()
        sampled_labels = label_rois(sampled_boxes, gt_boxes, threshold=labeling_threshold)
        n_stenosis = sum(sampled_labels)
        print(f"[WORKER]   label_rois done in {time.time()-t0:.2f}s"
              f" — {n_stenosis} stenosis / {len(sampled_labels)-n_stenosis} healthy", flush=True)

        # ── GT-centred boxes ──────────────────────────────────────
        all_boxes_and_labels = list(zip(sampled_boxes, sampled_labels))
        for gt_box in gt_boxes:
            cx    = (gt_box['xmin'] + gt_box['xmax']) // 2
            cy    = (gt_box['ymin'] + gt_box['ymax']) // 2
            fixed = _create_fixed_box(cx, cy, half_size, img_shape)
            all_boxes_and_labels.append((fixed, 1))
        print(f"[WORKER]   total boxes     : {len(all_boxes_and_labels)}"
              f" (100 sampled + {len(gt_boxes)} GT-centred)", flush=True)

        # ── Build rows ────────────────────────────────────────────
        rows = []
        for roi_idx, (box, lbl) in enumerate(all_boxes_and_labels, start=1):
            rows.append({
                'roi_name'   : f"{image_name}_{roi_idx}",
                'image_name' : image_name,
                'xmin'       : box['xmin'],
                'ymin'       : box['ymin'],
                'xmax'       : box['xmax'],
                'ymax'       : box['ymax'],
                'label'      : lbl,
            })

        print(f"[WORKER]   rows built      : {len(rows)}", flush=True)
        print(f"[WORKER] ── DONE  {image_name} in {time.time()-t_start:.2f}s ──", flush=True)
        return rows

    except Exception:
        print(f"[WORKER ERROR] Exception processing {img_path}", flush=True)
        print(traceback.format_exc(), flush=True)
        return []


def _extract_features_for_image(args, roi_size, half_size, labeling_threshold, gabor_bank, feature_cols):
    """
    Worker function: processes a single image and returns a list of feature row dicts.
    Must be a top-level function to be picklable by multiprocessing.
    """
    img_path, mask_path, skel_path, gt_boxes = args

    img      = load_image(img_path)
    mask     = load_image(mask_path)
    skeleton = load_image(skel_path)
    if img is None or mask is None or skeleton is None:
        return []

    img_shape = img.shape[:2]

    p          = Path(img_path)
    patient_id = p.parts[-3]
    serie_id   = p.parts[-2]
    frame_stem = p.stem.replace('_processed', '')
    image_name = f"{patient_id}_{serie_id}_{frame_stem}"

    print(f"Extracting features from image {frame_stem} of patient {patient_id}, serie {serie_id}")


    sampled_boxes  = extract_rois(skeleton, img_shape, roi_size=roi_size, total_rois=100)
    sampled_labels = label_rois(sampled_boxes, gt_boxes, threshold=labeling_threshold)

    all_boxes_and_labels = list(zip(sampled_boxes, sampled_labels))

    for gt_box in gt_boxes:
        cx = (gt_box['xmin'] + gt_box['xmax']) // 2
        cy = (gt_box['ymin'] + gt_box['ymax']) // 2
        fixed = _create_fixed_box(cx, cy, half_size, img_shape)
        all_boxes_and_labels.append((fixed, 1))

    rows = []
    for roi_idx, (box, lbl) in enumerate(all_boxes_and_labels, start=1):

        xmin, ymin = box['xmin'], box['ymin']
        xmax, ymax = box['xmax'], box['ymax']

        raw_crop  = img     [ymin:ymax, xmin:xmax]
        mask_crop = mask    [ymin:ymax, xmin:xmax]
        skel_crop = skeleton[ymin:ymax, xmin:xmax]

        if raw_crop.shape != (roi_size, roi_size):
            continue

        raw_feats   = extract_raw_roi_features(raw_crop)
        gabor_feats = apply_gabor_and_extract_features(raw_crop, gabor_bank)
        width_ratio = extract_width_ratio_feature(mask_crop, skel_crop)
        new_feats = extract_new_features(raw_crop, mask_crop)  # ← added

        full_feat_vector = np.concatenate([  # ← updated
            raw_feats,
            gabor_feats,
            [width_ratio],
            new_feats,
        ])

        feat_row = {'roi_name': f"{image_name}_{roi_idx}"}
        for col, val in zip(feature_cols, full_feat_vector):
            feat_row[col] = val
        feat_row['label'] = lbl
        rows.append(feat_row)

    return rows


def _compute_glcm(image_uint8, angle_deg, distance=1, levels=64):
    """
    Computes a single normalised symmetric GLCM matrix using numpy.
    Image is requantized to `levels` grey levels for efficiency.
    """
    # Requantize to `levels` bins
    img = (image_uint8.astype(np.float32) / 256.0 * levels).astype(np.uint8)
    img = np.clip(img, 0, levels - 1)

    h, w = img.shape
    angle_rad = np.deg2rad(angle_deg)
    dy = -int(round(distance * np.sin(angle_rad)))
    dx =  int(round(distance * np.cos(angle_rad)))

    # Source and target slices for the given offset (dy, dx)
    y_src = slice(max(0, -dy), h + min(0, -dy))
    y_tgt = slice(max(0,  dy), h + min(0,  dy))
    x_src = slice(max(0, -dx), w + min(0, -dx))
    x_tgt = slice(max(0,  dx), w + min(0,  dx))

    p_src = img[y_src, x_src].ravel()
    p_tgt = img[y_tgt, x_tgt].ravel()

    glcm = np.zeros((levels, levels), dtype=np.float64)
    np.add.at(glcm, (p_src, p_tgt), 1)

    # Symmetric: count both directions
    glcm = glcm + glcm.T

    total = glcm.sum()
    if total > 0:
        glcm /= total

    return glcm


def _glcm_properties(glcm, levels=64):
    """
    Computes contrast, correlation, energy (ASM) and homogeneity (IDM)
    from a normalised GLCM matrix.
    """
    I, J = np.meshgrid(np.arange(levels), np.arange(levels), indexing='ij')

    contrast    = float(np.sum(glcm * (I - J) ** 2))
    energy      = float(np.sum(glcm ** 2))
    homogeneity = float(np.sum(glcm / (1.0 + np.abs(I - J))))

    mu_i  = np.sum(I * glcm)
    mu_j  = np.sum(J * glcm)
    std_i = np.sqrt(np.sum(glcm * (I - mu_i) ** 2))
    std_j = np.sqrt(np.sum(glcm * (J - mu_j) ** 2))

    if std_i < 1e-10 or std_j < 1e-10:
        correlation = 0.0
    else:
        correlation = float(np.sum(glcm * (I - mu_i) * (J - mu_j)) / (std_i * std_j))

    return contrast, correlation, energy, homogeneity


def _extract_glcm_features(roi_uint8, levels=64):
    """
    16 GLCM features: contrast, correlation, energy, homogeneity
    each at 4 angles (0°, 45°, 90°, 135°).
    """
    angles   = [0, 45, 90, 135]
    features = []

    contrasts    = []
    correlations = []
    energies     = []
    homogeneities = []

    for angle in angles:
        glcm = _compute_glcm(roi_uint8, angle_deg=angle, levels=levels)
        c, r, e, h = _glcm_properties(glcm, levels=levels)
        contrasts.append(c)
        correlations.append(r)
        energies.append(e)
        homogeneities.append(h)

    # Paper order: all 4 angles per property
    features.extend(contrasts)
    features.extend(correlations)
    features.extend(energies)
    features.extend(homogeneities)

    return features  # 16 values


def _extract_radon_features(roi):
    """
    12 Radon transform features.
    Mean, Std, Variance of projections at 0°, 45°, 90°, 135°.

    Returns list of 12 values in paper order:
        mean × 4 angles | std × 4 angles | var × 4 angles
    """
    angles    = [0, 45, 90, 135]
    sinogram  = radon(roi.astype(np.float64), theta=angles, circle=False)
    # sinogram shape: (n_projections, 4)

    means = [float(np.mean(sinogram[:, i])) for i in range(4)]
    stds  = [float(np.std (sinogram[:, i])) for i in range(4)]
    vars_ = [float(np.var (sinogram[:, i])) for i in range(4)]

    return means + stds + vars_   # 12 values


def _extract_morphology_features(mask_roi):
    """
    12 region-based morphology / shape features extracted from the
    largest connected component in the binary mask.

    Returns list of 12 values in paper order:
        area, perimeter, major_axis_length, minor_axis_length,
        eccentricity, orientation, convex_area, filled_area,
        solidity, extent, equivalent_diameter, euler_number.

    Returns zeros if the mask contains no foreground pixels.
    """
    labeled     = sk_label(mask_roi.astype(np.uint8))
    props_list  = regionprops(labeled)

    if not props_list:
        return [0.0] * 12

    # Use the largest connected component
    region = max(props_list, key=lambda r: r.area)

    # equivalent_diameter was renamed in skimage 0.20
    try:
        equiv_diam = region.equivalent_diameter
    except AttributeError:
        equiv_diam = region.equivalent_diameter_area

    return [
        float(region.area),
        float(region.perimeter),
        float(region.major_axis_length),
        float(region.minor_axis_length),
        float(region.eccentricity),
        float(region.orientation),
        float(region.convex_area),
        float(region.filled_area),
        float(region.solidity),
        float(region.extent),
        float(equiv_diam),
        float(region.euler_number),
    ]


def extract_new_features(roi, mask_roi=None):
    """
    Extracts 47 features from a single ROI following the paper methodology.
    Applied to the full ROI only (no tiling).

    Feature groups:
        [ 0: 7 ]  First-order statistics          (7)
        [ 7:23 ]  GLCM texture features           (16)
        [23:35 ]  Radon transform features        (12)
        [35:47 ]  Vessel morphology/shape         (12)
                                            Total: 47

    Parameters:
        roi      : 2D numpy array (H, W), raw or processed grayscale crop
        mask_roi : 2D binary numpy array (H, W), vessel mask crop.
                   If None, Otsu thresholding is applied to roi internally.

    Returns:
        feature_vector : list of 47 floats
    """
    # Ensure uint8 for GLCM (which requires integer pixel values)
    if roi.dtype != np.uint8:
        roi_uint8 = cv2.normalize(roi, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    else:
        roi_uint8 = roi

    if mask_roi is None:
        _, binary = cv2.threshold(roi_uint8, 0, 1, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        mask_binary = binary
    else:
        mask_binary = (mask_roi > 0).astype(np.uint8)

    features = []
    features.extend(extract_stats(roi))  # 6  (reuses existing)
    features.extend(_extract_glcm_features(roi_uint8))  # 16
    features.extend(_extract_radon_features(roi))  # 12
    features.extend(_extract_morphology_features(mask_binary))  # 12
                                                    # Total: 46
    return features
