import numpy as np
import cv2
import matplotlib.pyplot as plt
from src.utils import load_image

def extract_rois(skeleton, img_shape, roi_size=80, total_rois=100):
    """
    Extracts exactly `total_rois` fixed-size ROIs along a vessel skeleton.
    This function is pure and can be used identically during training and inference.

    Args:
        skeleton (np.ndarray): Binary image of the skeletonized vessel.
        img_shape (tuple): Shape of the original image (height, width).
        roi_size (int): The height and width of the square ROI.
        total_rois (int): Total number of ROIs to sample (default 100).

    Returns:
        list of dict: Exactly `total_rois` candidate bounding boxes.
    """
    half_size = roi_size // 2

    # 1. Sort the skeleton points (The "Walker" Algorithm)
    y_coords, x_coords = np.where(skeleton)
    available_points = set(zip(x_coords, y_coords))
    ordered_points = []

    if len(available_points) > 0:
        actual = list(available_points)[0]
        ordered_points.append(actual)
        available_points.remove(actual)

        while len(available_points) > 0:
            missing_points = np.array(list(available_points))
            dists = np.sum((missing_points - np.array(actual)) ** 2, axis=1)
            idx_min = np.argmin(dists)

            actual = tuple(missing_points[idx_min])
            ordered_points.append(actual)
            available_points.remove(actual)

    # 2. Sample Equidistant points along the skeleton
    final_boxes = []
    total_points = len(ordered_points)

    if total_points > 0 and total_rois > 0:
        equidist_idxs = np.linspace(0, total_points - 1, total_rois, dtype=int)

        for idx in equidist_idxs:
            pt_x, pt_y = ordered_points[idx]
            final_boxes.append(_create_fixed_box(pt_x, pt_y, half_size, img_shape))

    return final_boxes


def _create_fixed_box(center_x, center_y, half_size, img_shape):
    """Helper function to create a bounding box and clamp it to image boundaries."""
    xmin = int(center_x - half_size)
    ymin = int(center_y - half_size)
    xmax = int(center_x + half_size)
    ymax = int(center_y + half_size)

    # Dynamic boundary adjustment to ensure the box is ALWAYS exactly 80x80
    # If it hits a border, we shift the box inward rather than cropping it
    if xmin < 0:
        xmax += abs(xmin)
        xmin = 0
    if ymin < 0:
        ymax += abs(ymin)
        ymin = 0
    if xmax > img_shape[1]:
        xmin -= (xmax - img_shape[1])
        xmax = img_shape[1]
    if ymax > img_shape[0]:
        ymin -= (ymax - img_shape[0])
        ymax = img_shape[0]

    return {'xmin': xmin, 'ymin': ymin, 'xmax': xmax, 'ymax': ymax}


def label_rois(candidate_rois, gt_boxes, threshold=0.40):
    """
    Labels a list of candidate ROIs based on their overlap with the original
    ground truth bounding boxes.

    Args:
        candidate_rois (list of dict): The 80x80 ROIs generated by extract_rois.
        gt_boxes (list of dict): The ORIGINAL, variable-sized ground truth boxes from the XML.
        threshold (float): The minimum overlap percentage required to label as stenosis.

    Returns:
        list of int: A list of labels (1 for STENOSIS, 0 for HEALTHY) corresponding
                     to each ROI in candidate_rois.
    """
    labels = []

    for roi in candidate_rois:
        is_stenosis = False

        for gt_box in gt_boxes:
            # Calculate intersection coordinates
            inter_xmin = max(roi['xmin'], gt_box['xmin'])
            inter_ymin = max(roi['ymin'], gt_box['ymin'])
            inter_xmax = min(roi['xmax'], gt_box['xmax'])
            inter_ymax = min(roi['ymax'], gt_box['ymax'])

            # Calculate intersection dimensions
            inter_w = max(0, inter_xmax - inter_xmin)
            inter_h = max(0, inter_ymax - inter_ymin)
            area_interseccion = inter_w * inter_h

            # Calculate original GT box area
            area_box_original = (gt_box['xmax'] - gt_box['xmin']) * (gt_box['ymax'] - gt_box['ymin'])

            # Check if threshold is met
            if area_box_original > 0 and area_interseccion >= threshold * area_box_original:
                is_stenosis = True
                break  # If it matches one GT box, no need to check others

        # Append 1 for STENOSIS, 0 for HEALTHY
        labels.append(1 if is_stenosis else 0)

    return labels


def build_gabor_bank(ksize=31, n_sizes=6, n_orientations=12):
    """
    Builds a bank of Gabor filters at various scales and orientations.

    Parameters:
        ksize          : int, the size of the kernel (e.g., 31 means a 31x31 matrix)
        n_sizes        : int, number of different frequencies/thicknesses to detect
        n_orientations : int, number of angles (e.g., 12 means every 15 degrees)

    Returns:
        filters        : list of cv2 Gabor kernels
    """
    filters = []

    # 1. Calculate orientations (theta) - e.g., 12 steps from 0 to 180 degrees (Pi)
    thetas = np.arange(0, np.pi, np.pi / n_orientations)

    # 2. Calculate wavelengths (lambda) - controls the thickness of the vessel we want to detect
    # A good range for an 80x80 image is wavelengths from roughly 4 pixels up to 16 pixels
    lambdas = np.linspace(4, 20, n_sizes)

    # Default parameters for medical imaging Gabor filters
    gamma = 0.5  # Spatial aspect ratio (0.5 makes it slightly elliptical, good for tubes)
    psi = 0  # Phase offset (0 makes it perfectly centered)

    for theta in thetas:
        for lamda in lambdas:
            # Sigma controls the size of the Gaussian envelope.
            # Tying it to lambda ensures the filter scales properly.
            sigma = 0.56 * lamda

            # Generate the kernel
            kernel = cv2.getGaborKernel(
                (ksize, ksize),
                sigma,
                theta,
                lamda,
                gamma,
                psi,
                ktype=cv2.CV_32F  # Using 32-bit floats for high precision
            )

            # Normalize the kernel (helps ensure different scales have comparable energy)
            kernel /= 1.5 * kernel.sum() if kernel.sum() != 0 else 1.0

            filters.append(kernel)

    print(f"Built Gabor bank with {len(filters)} filters ({n_orientations} orientations x {n_sizes} sizes).")
    return filters


def apply_gabor_and_extract_features(roi, filters):
    """
    Applies a bank of Gabor filters to a single ROI and extracts Mean and Variance.

    Parameters:
        roi     : 2D numpy array (your 80x80 image crop)
        filters : list of cv2 Gabor kernels generated by build_gabor_bank()

    Returns:
        feature_vector : 1D numpy array containing (Mean, Variance) for each filter
    """
    features = []

    for kernel in filters:
        # Apply the filter using cv2.filter2D
        # cv2.BORDER_REFLECT acts as a mirror at the edges, preventing black borders
        # cv2.CV_32F ensures we don't lose negative filter responses via clipping
        filtered_img = cv2.filter2D(roi, cv2.CV_32F, kernel, borderType=cv2.BORDER_REFLECT)

        # Calculate statistics
        mean_val = np.mean(filtered_img)
        var_val = np.var(filtered_img)

        # Append to our list
        features.append(mean_val)
        features.append(var_val)

    # Return as a flat numpy array (ready for PCA or an ML model)
    return np.array(features)


def plot_gabor_response_grid(roi, gabor_bank, title, n_orientations=12, n_sizes=6):
    """
    Applies 72 Gabor filters to an ROI and displays the responses in a
    structured 12 (orientations) x 6 (scales) grid.
    """
    # Re-calculate parameters for labels
    thetas = np.arange(0, np.pi, np.pi / n_orientations)
    lambdas = np.linspace(4, 18, n_sizes)

    # Setup the figure grid
    fig, axes = plt.subplots(n_orientations, n_sizes, figsize=(14, 24))
    fig.suptitle(title, fontsize=18, fontweight='bold', y=0.92)

    # Plot the original ROI in a text box style on top or just print it out
    for i, theta in enumerate(thetas):
        deg = int(np.degrees(theta))
        for j, lamda in enumerate(lambdas):
            ax = axes[i, j]

            # Map back to the linear filter bank array
            filter_idx = i * n_sizes + j
            kernel = gabor_bank[filter_idx]

            # Apply Gabor Filter (Mirror padding)
            filtered_img = cv2.filter2D(roi, cv2.CV_32F, kernel, borderType=cv2.BORDER_REFLECT)

            # Show response map
            ax.imshow(filtered_img, cmap='gray')
            ax.axis('off')

            # Set labels on the borders of the grid for clean interpretation
            if i == 0:
                ax.set_title(f"Size {j + 1}\n($\lambda$={lamda:.1f})", fontsize=10)
            if j == 0:
                ax.text(-15, 40, f"{deg}°", va='center', ha='right', fontsize=12, fontweight='bold')

    plt.tight_layout()
    plt.show()